#!/bin/bash
. "${HOME}/.cache/wal/colors.sh"

./.fehbg
wal -R
# nitrogen --restore &
picom --experimental-backends &
nm-applet &
dunst -sep_color "$background" -frame_color "$color4" -nf "$foreground" -lf "$foreground" -cf "$foreground" &
kdeconnect-indicator &
urxvtd -q -o -f &
usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
