#!/bin/sh

# Generates zathura configuration file

. $HOME/.cache/wal/colors.sh

cat <<CONF
#  _______         __   __                     
# |__     |.---.-.|  |_|  |--.--.--.----.---.-.
# |     __||  _  ||   _|     |  |  |   _|  _  |
# |_______||___._||____|__|__|_____|__| |___._|


# colors
set default-bg "$background"
set default-fg "$foreground"

set completion-bg "$background"
set completion-fg "$foreground"
set completion-group-bg "$background"
set completion-group-fg "$color2"
set completion-highlight-bg "$foreground"
set completion-highlight-fg "$background"

set recolor-lightcolor "$background"
set recolor-darkcolor "$foreground"

set inputbar-bg "$background"
set inputbar-fg "$foreground"

set notification-bg "$background"
set notification-fg "$foreground"
set notification-error-bg "$color1"
set notification-error-fg "$foreground"
set notification-warning-bg "$color1"
set notification-warning-fg "$foreground"

set statusbar-bg "$background"
set statusbar-fg "$foreground"

set index-bg "$background"
set index-fg "$foreground"

set index-active-bg "$foreground"
set index-active-fg "$background"
set render-loading-bg "$background"
set render-loading-fg "$foreground"

# font
set font "Roboto 9"

# settings
set window-height 700
set window-width 500
set adjust-open width
set page-padding 8
set show-hidden true
set statusbar-basename true
set statusbar-home-tilde true
set page-right-to-left true
set recolor true
set recolor-reverse-video true
set selection-clipboard clipboard

# remove default key bindings
unmap <C-n>

# key bindings
map K navigate previous
map J navigate next
map D toggle_page_mode
map b toggle_statusbar
map P print
map r reload
map R rotate
map + zoom in
map - zoom out
map d recolor
map <C-q> quit
CONF
