#!/bin/bash

#		  __                         
# .-----.|  |.---.-.--.--.-----.----.
# |  _  ||  ||  _  |  |  |  -__|   _|
# |   __||__||___._|___  |_____|__|  
# |__|             |_____|           

# Author: Dilip Chauhan
# Github: https://github/TechnicalDC

# This script requires mpc

case $1 in
	"toggle")
		mpc toggle 
		state=$(mpc status %state%)
		notify-send -a 'MPC' "Player $state." -i 'dialog-information' -t 2000
		;;
	"next")
		mpc next 
		current=$(mpc current)
		notify-send -a 'MPC' "Playing $current." -i 'dialog-information' -t 2000
		;;
	"prev")
		mpc prev 
		current=$(mpc current)
		notify-send -a 'MPC' "Playing $current." -i 'dialog-information' -t 2000
		;;
esac
