#!/bin/bash

# .-----.-----.--.--.--.-----.----.--------.-----.-----.--.--.
# |  _  |  _  |  |  |  |  -__|   _|        |  -__|     |  |  |
# |   __|_____|________|_____|__| |__|__|__|_____|__|__|_____|
# |__|

# Author: Dilip Chauhan
# Github: https://github/TechnicalDC

USE_ICON="no"

option1="Lock"
option2="Logout"
option3="Reboot"
option4="Shutdown"

if [ "$USE_ICON" =  "yes" ]; then
option1=" "
option2=" "
option3=" "
option4=" "
fi

options="$option1\n"
options="$options$option2\n"
options="$options$option3\n$option4"

choice=$(echo -e "$options" | walker -d)
# choice=$(echo -e "$options" | rofi -dmenu -i -no-show-icons -p "session" -l 4)

case $choice in
	$option1)
	   hyprlock -c $HOME/.config/hypr/hyprlock.conf ;;
	$option2)
      # choice=$(echo "$yes|$no" | rofi -dmenu -sep "|" -theme ~/.config/rofi/themes/pywal/dialog.rasi -mesg "Are you sure?")
      # if [[ $choice == $yes ]]; then
         hyprctl dispatch exit || niri msg action quit
      # fi ;;
      ;;
	$option3)
      # choice=$(echo "$yes|$no" | rofi -dmenu -sep "|" -theme ~/.config/rofi/themes/pywal/dialog.rasi -mesg "Are you sure?")
      # if [[ $choice == $yes ]]; then
         systemctl reboot
      # fi ;;
      ;;
	$option4)
      # choice=$(echo "$yes|$no" | rofi -dmenu -sep "|" -theme ~/.config/rofi/themes/pywal/dialog.rasi -mesg "Are you sure?")
      # if [[ $choice == $yes ]]; then
         systemctl poweroff
      # fi ;;
      ;;
esac

