#!/bin/bash

# .-----.-----.--.--.--.-----.----.--------.-----.-----.--.--.
# |  _  |  _  |  |  |  |  -__|   _|        |  -__|     |  |  |
# |   __|_____|________|_____|__| |__|__|__|_____|__|__|_____|
# |__|

# Author: Dilip Chauhan
# Github: https://github/TechnicalDC

yes=" Ok"
no="󰜺 Cancel"
option1=" Lock"
option2=" Logout"
option3=" Restart"
option4=" Shutdown"

options="$option1\n"
options="$options$option2\n"
options="$options$option3\n$option4"

choice=$(echo -e "$options" | rofi -dmenu -theme ~/.config/rofi/themes/solid/powermenu.rasi -i -no-show-icons)
yes=$choice

case $choice in
	$option1)
	   hyprlock -c $HOME/.config/hypr/themes/solid/hyprlock.conf ;;
	$option2)
      # choice=$(echo "$yes|$no" | rofi -dmenu -sep "|" -theme ~/.config/rofi/themes/pywal/dialog.rasi -mesg "Are you sure?")
      # if [[ $choice == $yes ]]; then
         hyprctl dispatch exit
      # fi ;;
      ;;
	$option3)
      # choice=$(echo "$yes|$no" | rofi -dmenu -sep "|" -theme ~/.config/rofi/themes/pywal/dialog.rasi -mesg "Are you sure?")
      # if [[ $choice == $yes ]]; then
         systemctl reboot
      # fi ;;
      ;;
	$option4)
      # choice=$(echo "$yes|$no" | rofi -dmenu -sep "|" -theme ~/.config/rofi/themes/pywal/dialog.rasi -mesg "Are you sure?")
      # if [[ $choice == $yes ]]; then
         systemctl poweroff
      # fi ;;
      ;;
esac

