#!/bin/bash

# .-----.-----.--.--.--.-----.----.--------.-----.-----.--.--.
# |  _  |  _  |  |  |  |  -__|   _|        |  -__|     |  |  |
# |   __|_____|________|_____|__| |__|__|__|_____|__|__|_____|
# |__|

# Author: Dilip Chauhan
# Github: https://github/TechnicalDC

option1=""
option2=""
option3=""
option4=""

options="$option1\n"
options="$options$option2\n"
options="$options$option3\n$option4"

choice=$(echo -e "$options" | rofi -dmenu -theme ~/.config/rofi/themes/catppuccin-macchiato-powermenu.rasi -i -no-show-icons -lines 4)

case $choice in
	$option1)
	   hyprlock ;;
	$option2)
		bspc quit || i3-msg exit || herbstclient quit || hyprctl dispatch exit ;;
	$option3)
		systemctl reboot ;;
	$option4)
		systemctl poweroff ;;
esac

