#!/bin/bash

#  __                 __                         __
# |  |--.-----.-----.|  |--.--------.---.-.----.|  |--.-----.
# |  _  |  _  |  _  ||    <|        |  _  |   _||    <|__ --|
# |_____|_____|_____||__|__|__|__|__|___._|__|  |__|__|_____|


# Author: Dilip Chauhan
# Github: https://github/TechnicalDC

# This script requires rofi and qutebrowser to work (if you prefer other
# browser than replace qutebrowser command with command that launch your
# browser)

FILE="$HOME/.config/qutebrowser/bookmarks.txt"

if [ ! -f $FILE ]; then
	touch $FILE
fi

URL=$(cat $FILE | cut -d' ' -f1 | rofi -dmenu -i -p 'bookmarks' -no-show-icons)
if grep -q "$URL" $FILE ; then
	wl-copy $URL
else
	echo $URL >> $FILE
fi
