#!/bin/bash

#             __ _                   _
#  _ __ ___  / _(_)  _ __ ___   __ _(_)_ __ ___
# | '__/ _ \| |_| | | '_ ` _ \ / _` | | '_ ` _ \
# | | | (_) |  _| | | | | | | | (_| | | | | | | |
# |_|  \___/|_| |_| |_| |_| |_|\__,_|_|_| |_| |_|

# Author: Dilip Chauhan
# Github: https://github/TechnicalDC

# This script requires grim and slurp

DIR="$HOME/Pictures/screenshots/"
REL_DIR="~/Pictures/screenshots/"
NAME="grim_$(date +%d%m%Y_%H%M%S).png"
ROFI_THEME="$HOME/.config/rofi/themes/style-3/screenshot.rasi"
USE_ICON="no"

option1="Capture all screens"
option2="Capture screen"
option3="Capture screen with delay"
option4="Capture selection"
option5="Open with Gimp"

if [ "$USE_ICON" =  "yes" ]; then
	option1="󰍹 "
	option3="󰄉 "
	option4=" "
	option5=" "
fi

delayoption1="After 3 sec delay"
delayoption2="After 5 sec delay"
delayoption3="After 10 sec delay"

options="$option1\n$option2\n$option3\n$option4\n$option5"

get_monitor () {
   niri msg -j focused-output | jq .name | tr '"' ' '
}

choice=$(echo -e "$options" | rofi -i -dmenu -no-show-icons -no-sidebar-mode -theme $ROFI_THEME -l 4)

case $choice in
   $option1)
      sleep 1
      grim $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000 ;;
   $option2)
      sleep 1
      grim -o $(get_monitor) $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000 ;;
   $option3)
      delayoptions="$delayoption1\n$delayoption2\n$delayoption3"
      delay=$(echo -e "$delayoptions" | rofi -i -dmenu -no-show-icons -no-sidebar-mode -l 3 -theme $ROFI_THEME)

      case $delay in
         $delayoption1)
            sleep 3; grim -o $(get_monitor) $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000 ;;
         $delayoption2)
            sleep 5; grim -o $(get_monitor) $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000 ;;
         $delayoption3)
            sleep 10; grim -o $(get_monitor) $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000 ;;
      esac ;;

   $option4)
      grim -g "$(slurp)" $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i 'dialog-information' -t 2000 ;;
   $option5)
      sleep 1
      grim $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000
      gimp --no-splash --new-instance $DIR$NAME ;;
esac
