#!/bin/bash

#             __ _                   _           
#  _ __ ___  / _(_)  _ __ ___   __ _(_)_ __ ___  
# | '__/ _ \| |_| | | '_ ` _ \ / _` | | '_ ` _ \ 
# | | | (_) |  _| | | | | | | | (_| | | | | | | |
# |_|  \___/|_| |_| |_| |_| |_|\__,_|_|_| |_| |_|

# Author: Dilip Chauhan
# Github: https://github/TechnicalDC

# This script requires scrot

DIR="$HOME/Pictures/screenshots/"
NAME="maim_$(date +%d%m%Y_%H%M%S).png"

option1="  Entire screen"
option2="  Entire screen with delay"
option3="  Selection"

options="$option1\n$option2\n$option3"

choice=$(echo -e "$options" | rofi -mesg "Current: $DIR" -theme $ROFI_MINI -i -dmenu -no-show-icons -no-sidebar-mode -lines 4 -width 30 -p "  ") 

case $choice in
	$option1)
		maim -u $DIR$NAME && notify-send -a 'Maim' 'Screenshot saved.' -i 'dialog-information' -t 2000 ;; 
	$option2)
		delayoption1="Take screenshot with 3 sec delay"
		delayoption2="Take screenshot with 5 sec delay"
		delayoption3="Take screenshot with 10 sec delay"
		delayoptions="$delayoption1\n$delayoption2\n$delayoption3"
		delay=$(echo -e "$delayoptions" | rofi -theme $ROFI_MINI -i -dmenu -no-show-icons -no-sidebar-mode -lines 3 -width 30 -p "  ") 

		case $delay in
			$delayoption1)
				maim -u -d 3 $DIR$NAME && notify-send -a 'Maim' 'Screenshot saved.' -i 'dialog-information' -t 2000 ;; 
			$delayoption2)
				maim -u -d 5 $DIR$NAME && notify-send -a 'Maim' 'Screenshot saved.' -i 'dialog-information' -t 2000 ;; 
			$delayoption3)
				maim -u -d 10 $DIR$NAME && notify-send -a 'Maim' 'Screenshot saved.' -i 'dialog-information' -t 2000 ;; 
		esac ;;

	$option3)
		maim -s $DIR$NAME && notify-send -a 'Maim' 'Screenshot saved.' -i 'dialog-information' -t 2000 ;;
esac
