#!/bin/bash

#             __ _                   _
#  _ __ ___  / _(_)  _ __ ___   __ _(_)_ __ ___
# | '__/ _ \| |_| | | '_ ` _ \ / _` | | '_ ` _ \
# | | | (_) |  _| | | | | | | | (_| | | | | | | |
# |_|  \___/|_| |_| |_| |_| |_|\__,_|_|_| |_| |_|

# Author: Dilip Chauhan
# Github: https://github/TechnicalDC

# This script requires grim and slurp

DIR="$HOME/Pictures/screenshots/"
REL_DIR="~/Pictures/screenshots/"
NAME="grim_$(date +%d%m%Y_%H%M%S).png"
USE_ICON="no"

option1="Capture screen"
option2="Capture screen with delay"
option3="Capture selection"
option4="Open with Gimp"

if [ "$USE_ICON" =  "yes" ]; then
	option1="󰍹 "
	option2="󰄉 "
	option3=" "
	option4=" "
fi

delayoption1="After 3 sec delay"
delayoption2="After 5 sec delay"
delayoption3="After 10 sec delay"

options="$option1\n$option2\n$option3\n$option4"

choice=$(echo -e "$options" | walker --dmenu --height 300)
# choice=$(echo -e "$options" | rofi -i -dmenu -no-show-icons -no-sidebar-mode -p "screenshot" -l 4)
#

case $choice in
   $option1)
      sleep 1
      grim $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000 ;;
   $option2)
      delayoptions="$delayoption1\n$delayoption2\n$delayoption3"
      delay=$(echo -e "$delayoptions" | rofi -i -dmenu -no-show-icons -no-sidebar-mode -l 3)

      case $delay in
         $delayoption1)
            sleep 3; grim $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000 ;;
         $delayoption2)
            sleep 5; grim $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000 ;;
         $delayoption3)
            sleep 10; grim $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000 ;;
      esac ;;

   $option3)
      grim -g "$(slurp)" $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i 'dialog-information' -t 2000 ;;
   $option4)
      sleep 1
      grim $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000
      gimp --no-splash --new-instance $DIR$NAME ;;
esac
