#!/usr/bin/env bash

JOURNAL_DIR="$HOME/Notes/journal/$(date +%Y)/$(date +%m)"
JOURNAL="$JOURNAL_DIR/$(date +%d_%m_%Y).md"

session=$(tmux ls | grep attached | cut -d ":" -f 1)

case $session in
   "work")
      tmux send -t $session:1 "nvim ~/Notes/todo.md" ENTER

      tmux new-window -t $session:2

      if [[ ! -d "$JOURNAL_DIR" ]]; then
         mkdir -p $JOURNAL_DIR
         echo "# $(date +%m,%Y)" > $JOURNAL_DIR/index.md
      fi
      if [[ ! -f "$JOURNAL_DIR/$(date +%d_%m_%Y).md" ]]; then
         echo "# $(date +%d/%m/%Y)" > $JOURNAL
         echo "- [$(date +%d)](./$(date +%d_%m_%Y).md)" >> $JOURNAL_DIR/index.md
      fi

      tmux send -t $session:2 "nvim $JOURNAL" ENTER
      ;;
esac
