#!/usr/bin/env sh

TMUX_POPUP_OPTS="-b double -w 70% -h 70%"

case $1 in
   "todo")
      tmux display-popup $TMUX_POPUP_OPTS -E "nvim $HOME/Notes/todo.md"
      ;;
   "note")
      tmux display-popup $TMUX_POPUP_OPTS -E "nvim $HOME/Notes/"
      ;;
   "nnn")
      tmux display-popup $TMUX_POPUP_OPTS -E "nnn"
      ;;
   "persist")
      tmux display-popup $TMUX_POPUP_OPTS -E "tmux attach -t persist || tmux new-session -s persist"
      ;;
esac
