#!/usr/bin/env bash

HOSTNAME=$(grep "Host " $HOME/.ssh/config | cut -d' ' -f2 | fzf --tmux --border double --prompt "[ssh] ")

if [ -n "$HOSTNAME" ]; then
   tmux new-window -n "ssh - $HOSTNAME" ssh $HOSTNAME
   case $HOSTNAME in
      dev*)
         tmux select-pane -P 'bg=#000000,fg=#00ff00' ;;
      *)
         tmux select-pane -P 'bg=#000000,fg=#ffffff' ;;
   esac
fi
