#!/bin/bash

#				   __ __        
# .--.--.--.---.-.|  |  |.--.--.
# |  |  |  |  _  ||  |  ||  |  |
# |________|___._||__|__||___  |
#					     |_____|
# Github: https://github.com/TechnicalDC/dc-scripts


THEME="$HOME/.config/rofi/themes/fancy.rasi"
WALLPAPERS_DIR="$HOME/Wallpapers"

option1="  Set wallpaper"
option2="  Set colorscheme"
option3="  Generate colorscheme from image"
option4="  Exit"

options="$option1\n$option2\n$option3\n$option4"

choice=$(echo -e "$options" | rofi -theme $THEME -i -dmenu -no-show-icons -no-sidebar-mode -lines 4 -width 30 -p " ") 

post_run () {
	echo $1
	xrdb $HOME/.Xresources
	sed -i "s| .\+| "$1"]]|" $HOME/.config/nvim/lua/colors/init.lua
	genstarttree

	# script that generates zathurarc
	bash $HOME/.scripts/gendunstrc >> ~/.config/dunst/dunstrc
	bash $HOME/.scripts/genzathurarc >> ~/.config/zathura/zathurarc
	bash $HOME/.scripts/wal-telegram --wal

	pkill dunst

	dunstify -a 'Wally' 'Theme changed.' -t 1000
}

case $choice in
	$option1)
		WALLPAPER=$(sxiv -ot -N imagepicker $WALLPAPERS_DIR/*.jpg $WALLPAPERS_DIR/*.png $WALLPAPERS_DIR/*.jpeg $WALLPAPERS_DIR/*.webp)
		feh --bg-fill $WALLPAPER 
		cp $WALLPAPER ~/.cache/wal/wallpaper.jpg
		mantablockscreen -i $WALLPAPER &
		dunstify -a 'Wally' 'Wallpaper changed.' -t 1000 -I $WALLPAPER
		;;
	$option2)
		COLOR=$(wal --theme | grep base16- | cut -d'-' -f2- | sort | uniq | rofi -i -dmenu -p ' ' -no-show-icons -no-sidebar-mode -lines 4 -width 30)
		if [ "$COLOR" != "" ] ; then
			wal --theme $COLOR
			post_run $COLOR
		fi
		;;
	$option3)
		WALLPAPER=$(sxiv -ot -N imagepicker $WALLPAPERS_DIR/*.jpg $WALLPAPERS_DIR/*.png $WALLPAPERS_DIR/*.jpeg $WALLPAPERS_DIR/*.webp)
		feh --bg-fill $WALLPAPER 
		wal -i $WALLPAPER
		post_run pywal $WALLPAPER
		mantablockscreen -i $WALLPAPER &
		dunstify -a 'Wally' 'Theme changed.' -t 1000 -I $WALLPAPER
		;;
	$option4)
		dunstify -a 'Wally' 'Exited.' -t 1000
		exit ;;
esac

