#!/bin/bash

#				   __ __        
# .--.--.--.---.-.|  |  |.--.--.
# |  |  |  |  _  ||  |  ||  |  |
# |________|___._||__|__||___  |
#					     |_____|

cp $1 ~/.cache/wal/wallpaper.jpg

# nitrogen --save --set-zoom-fill $fullpath &&
feh --bg-fill $1 &&
wal -i $1 &&
xrdb $HOME/.Xresources
mantablockscreen -i $1 

# script that generates zathurarc
genzathurarc >> ~/.config/zathura/zathurarc
wal-telegram --wal
notify-send -a 'Sxiv' 'Theme changed...' -i 'nitrogen' 
