#!/bin/bash

#				   __ __        
# .--.--.--.---.-.|  |  |.--.--.
# |  |  |  |  _  ||  |  ||  |  |
# |________|___._||__|__||___  |
#					     |_____|
# Github: https://github.com/TechnicalDC/dc-scripts


THEME="$HOME/.config/rofi/themes/minimal_dialog.rasi"
WALLPAPERS_DIR="$HOME/Wallpapers"
COLORSCHEMES_DIR="$HOME/.config/wal/colorschemes/dark"

option1="Set wallpaper"
option2="Set colorscheme"
option3="Generate colorscheme from image"
option4="Exit"

options="$option1\n$option2\n$option3\n$option4"

choice=$(echo -e "$options" | rofi -theme $THEME -i -dmenu -no-show-icons -no-sidebar-mode -lines 4 -width 30 -p " " -location 0 -yoffset 0 -fixed-num-lines true) 

post_run () {
	xrdb $HOME/.Xresources
	genstarttree
	sed -i "/colorscheme/s/ [Aa-Zz]\+/ $1/" $HOME/.config/nvim/lua/colors/init.lua
	sed -i "/theme =/s/themes\[\"[Aa-Zz]\+\"\],/themes[\"$1\"\]," $HOME/.config/nvim/lua/plugins-config/lualine.lua
	mantablockscreen -i $2 &

	# script that generates zathurarc
	bash $HOME/.scripts/gendunstrc >> ~/.config/dunst/dunstrc
	bash $HOME/.scripts/genzathurarc >> ~/.config/zathura/zathurarc
	bash $HOME/.scripts/wal-telegram --wal

	pkill dunst

	dunstify -a 'Wally' 'Theme changed.' -t 1000
}

case $choice in
	$option1)
		WALLPAPER=$(sxiv -ot -N imagepicker $WALLPAPERS_DIR/*.jpg $WALLPAPERS_DIR/*.png $WALLPAPERS_DIR/*.jpeg $WALLPAPERS_DIR/*.webp)
		feh --bg-fill $WALLPAPER 
		cp $WALLPAPER ~/.cache/wal/wallpaper.jpg
		mantablockscreen -i $1 &
		dunstify -a 'Wally' 'Wallpaper changed.' -t 1000 -I $WALLPAPER
		;;
	$option2)
		COLOR=$(ls $COLORSCHEMES_DIR | cut -d'.' -f1 | rofi -theme $THEME -i -dmenu -no-show-icons -no-sidebar-mode -lines 4 -width 30 -location 0 -yoffset 0 -fixed-num-lines true)
		if [ "$COLOR" != "" ] ; then
			wal --theme $COLORSCHEMES_DIR/$COLOR.json
			post_run $COLOR $WALLPAPER
		fi
		;;
	$option3)
		WALLPAPER=$(sxiv -ot -N imagepicker $WALLPAPERS_DIR/*.jpg $WALLPAPERS_DIR/*.png $WALLPAPERS_DIR/*.jpeg $WALLPAPERS_DIR/*.webp)
		feh --bg-fill $WALLPAPER 
		wal -i $WALLPAPER
		post_run pywal $WALLPAPER
		dunstify -a 'Wally' 'Theme changed.' -t 1000 -I $WALLPAPER
		;;
	$option4)
		dunstify -a 'Wally' 'Exited.' -t 1000
		exit ;;
esac

